services:
  - type: web
    name: discord-shop-bot
    runtime: python3
    buildCommand: pip install -r render-requirements.txt
    startCommand: python shopbot.py
    plan: free
    autoDeploy: false  # ปิด auto-deploy เพื่อลด restart
    envVars:
      - key: RENDER
        value: true
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PIP_CACHE_DIR
        value: /opt/render/project/.cache/pip
    healthCheckPath: /health
    preDeployCommand: echo "Pre-deploy setup..."
    scaling:
      minInstances: 1
      maxInstances: 1